In [202]:
import tensorflow as tf
import numpy as np
import pandas as pd
'''
sess = tf.compat.v1.Session()
sess.run(tf.compat.v1.global_variables_initializer())
for epoch in range(101):
    for (_x, _y) in zip(x_data, y_data):
        sess.run(train, feed_dict={X: _x, Y: _y})
    if epoch%5000==0:
        print("# cost: ", sess.run(cost, feed_dict={X: x_data, Y: y_data}))
#ValueError: Cannot feed value of shape (0, 31399, 50) for Tensor 'Placeholder_24:0', which has shape '(1, 50)'
'''

'\nsess = tf.compat.v1.Session()\nsess.run(tf.compat.v1.global_variables_initializer())\nfor epoch in range(101):\n    for (_x, _y) in zip(x_data, y_data):\n        sess.run(train, feed_dict={X: _x, Y: _y})\n    if epoch%5000==0:\n        print("# cost: ", sess.run(cost, feed_dict={X: x_data, Y: y_data}))\n#ValueError: Cannot feed value of shape (0, 31399, 50) for Tensor \'Placeholder_24:0\', which has shape \'(1, 50)\'\n'

In [203]:
import csv
from math import sin

a = []
A = 0.1
i = A
cnt = i
while i<=3.14:
    q = []
    q.append(cnt)
    for j in range(2,11,2):
        #ins = round(i**j,j)
        q.append(i**j)
    q.append(sin(i))
    
    a.append(q)
    #print(q)
    #print('##',a)
    i += A
    cnt += A

with open('sinL.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    for i in a:
        writer.writerow(i)

In [204]:
init = tf.compat.v1.global_variables_initializer()

In [205]:
data = pd.read_csv('sinL.csv', sep=',')
print(data[:1])

   0.1  0.010000000000000002  0.00010000000000000002  1.0000000000000004e-06  \
0  0.2                  0.04                  0.0016                0.000064   

   1.0000000000000005e-08  1.0000000000000006e-10  0.09983341664682815  
0                0.000003            1.024000e-07             0.198669  


In [206]:
xy = np.array(data, dtype=np.float32)

In [207]:
x_data = xy[:, 1:-1]
y_data = xy[:, [-1]]
print(len(xy),len(xy[0]))
#print(xy)
print(len(x_data),len(x_data[0]))
print(len(y_data),len(y_data[0]))
print(y_data[:5])
print(x_data[:2])
#x_data = x_data.reshape((-1,31399,50))
#y_data = y_data.reshape((-1,31399,1))

30 7
30 5
30 1
[[0.19866933]
 [0.29552022]
 [0.38941833]
 [0.47942555]
 [0.5646425 ]]
[[4.0000e-02 1.6000e-03 6.4000e-05 2.5600e-06 1.0240e-07]
 [9.0000e-02 8.1000e-03 7.2900e-04 6.5610e-05 5.9049e-06]]


In [208]:
X = tf.compat.v1.placeholder(tf.float32, shape=[None, 5])
Y = tf.compat.v1.placeholder(tf.float32, shape=[None, 1]) #None은 아무숫자나 가능하다는 의미
W = tf.Variable(tf.random.normal([5,1], mean=0.1014, stddev=0.1), name="weight")
b = tf.Variable(tf.random.normal([1]), name="bias")
#b = tf.cast(b, dtype=tf.float64)

In [209]:
hypothesis = 1 + tf.matmul(X, W) 

In [210]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=1e-10)
train = optimizer.minimize(cost)

In [216]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        cost_, hypo_, _ = sess.run([cost,hypothesis, train] , feed_dict={X: x_data, Y: y_data})
        if step%1000==0:
            print(step,cost_,hypo_[:3])
    print("###")
    print(sess.run(W))
    w0 = sess.run(W)
    print(sess.run(hypothesis, feed_dict={X:[[2.25,5.0625,11.390625,25.62890625,57.66503906]]}))
    

0 13729903.0 [[1.0015717]
 [1.0039457]
 [1.0082386]]
1000 2994.1792 [[1.0015686]
 [1.0039331]
 [1.0081757]]
2000 2917.1885 [[1.0015672]
 [1.0039289]
 [1.0081635]]
3000 2842.1802 [[1.0015659]
 [1.0039247]
 [1.0081514]]
4000 2769.1206 [[1.0015646]
 [1.0039207]
 [1.0081394]]
5000 2697.9246 [[1.0015633]
 [1.0039166]
 [1.0081273]]
6000 2628.5457 [[1.001562 ]
 [1.0039126]
 [1.0081154]]
7000 2560.9568 [[1.0015609]
 [1.0039089]
 [1.0081043]]
8000 2495.124 [[1.0015597]
 [1.0039052]
 [1.0080934]]
9000 2430.983 [[1.0015587]
 [1.0039015]
 [1.0080824]]
10000 2368.4844 [[1.0015575]
 [1.0038979]
 [1.0080714]]
###
[[ 0.03577676]
 [ 0.07584766]
 [ 0.07187279]
 [ 0.172712  ]
 [-0.02034253]]
[[5.536519]]


In [215]:
w0

array([[ 0.2449404 ],
       [ 0.09231102],
       [ 0.25182733],
       [ 0.11142299],
       [-0.01582397]], dtype=float32)